src/Entity/Reponse.php
<?php

namespace App\Entity;

use App\Repository\ReponseRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ReponseRepository::class)
 */
class Reponse
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    public $id_rep;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $reponse;


    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    public function getIdRep(): ?int
    {
        return $this->id_rep;
    }

    public function getReponse(): ?string
    {
        return $this->reponse;
    }

    public function setReponse(string $reponse): self
    {
        $this->reponse = $reponse;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }
}

src/Form/ReponseType.php
<?php

namespace App\Form;

use App\Entity\Reponse;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ReponseType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('reponse')
            ->add('createdAt')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Reponse::class,
        ]);
    }
}

src/Controller/ReponseController.php
<?php

namespace App\Controller;

use App\Entity\Reponse;
use App\Form\ReponseType;
use App\Repository\ReponseRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/reponse")
 */
class ReponseController extends AbstractController
{
    /**
     * @Route("/", name="app_reponse_index", methods={"GET"})
     */
    public function index(ReponseRepository $reponseRepository): Response
    {
        return $this->render('reponse/index.html.twig', [
            'reponses' => $reponseRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_reponse_new", methods={"GET", "POST"})
     */
    public function new(Request $request, ReponseRepository $reponseRepository): Response
    {
        $reponse = new Reponse();
        $form = $this->createForm(ReponseType::class, $reponse);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $reponseRepository->add($reponse);
            return $this->redirectToRoute('app_reponse_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('reponse/new.html.twig', [
            'reponse' => $reponse,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id_rep}", name="app_reponse_show", methods={"GET"})
     */
    public function show(Reponse $reponse): Response
    {
        return $this->render('reponse/show.html.twig', [
            'reponse' => $reponse,
        ]);
    }

    /**
     * @Route("/{id_rep}/edit", name="app_reponse_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Reponse $reponse, ReponseRepository $reponseRepository): Response
    {
        $form = $this->createForm(ReponseType::class, $reponse);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $reponseRepository->add($reponse);
            return $this->redirectToRoute('app_reponse_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('reponse/edit.html.twig', [
            'reponse' => $reponse,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id_rep}", name="app_reponse_delete", methods={"POST"})
     */
    public function delete(Request $request, Reponse $reponse, ReponseRepository $reponseRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$reponse->getId_rep(), $request->request->get('_token'))) {
            $reponseRepository->remove($reponse);
        }

        return $this->redirectToRoute('app_reponse_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/reponse/_delete_form.html.twig
<form method="post" action="{{ path('app_reponse_delete', {'id_rep': reponse.id_rep}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ reponse.id_rep) }}">
    <button class="btn">Delete</button>
</form>

templates/reponse/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/reponse/edit.html.twig
{% extends 'admin.html.twig' %}
{% block title %}Edit Reponse{% endblock %}


{% block body %}
    <h1>Edit Reponse</h1>

    {{ include('reponse/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_reponse_index') }}">back to list</a>

    {{ include('reponse/_delete_form.html.twig') }}
{% endblock %}

templates/reponse/index.html.twig
{% extends 'admin.html.twig' %}
{% block title %}Reponse index{% endblock %}

{% block body %}
    <h1>Reponse index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id_rep</th>
                <th>Reponse</th>
                <th>CreatedAt</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for reponse in reponses %}
            <tr>
                <td>{{ reponse.idRep }}</td>
                <td>{{ reponse.reponse }}</td>
                <td>{{ reponse.createdAt ? reponse.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('app_reponse_show', {'id_rep': reponse.id_rep}) }}">show</a>
                    <a href="{{ path('app_reponse_edit', {'id_rep': reponse.id_rep}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_reponse_new') }}">Create new</a>
{% endblock %}

templates/reponse/new.html.twig
{% extends 'admin.html.twig' %}
{% block title %}New Reponse{% endblock title %}

{% block body %}
    <h1>Create new Reponse</h1>

    {{ include('reponse/_form.html.twig') }}

    <a href="{{ path('app_reponse_index') }}">back to list</a>
{% endblock %}

templates/reponse/show.html.twig
{% extends 'admin.html.twig' %}
{% block title %}Reponse{% endblock %}

{% block body %}
    <h1>Reponse</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id_rep</th>
                <td>{{ reponse.idRep }}</td>
            </tr>
            <tr>
                <th>Reponse</th>
                <td>{{ reponse.reponse }}</td>
            </tr>
            <tr>
                <th>CreatedAt</th>
                <td>{{ reponse.createdAt ? reponse.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_reponse_index') }}">back to list</a>

    <a href="{{ path('app_reponse_edit', {'id_rep': reponse.id_rep}) }}">edit</a>

    {{ include('reponse/_delete_form.html.twig') }}
{% endblock %}