src/Entity/Club.php
<?php

namespace App\Entity;

use App\Repository\ClubRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ClubRepository::class)
 */
class Club
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    public $nom_club;

    /**
     * @ORM\Column(type="date")
     */
    public $date_creation;

    /**
     * @ORM\Column(type="string", length=255)
     */
    public $club_owner;

    /**
     * @ORM\Column(type="integer")
     */
    public $nbr_members;

    /**
     * @ORM\Column(type="string", length=255)
     * Assert\NotBlank(message="Please upload an image")
     * Assert\File(mimeTypes={"image/png", "image/jpeg"})
     */
    private $imageclb;






    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom_club(): ?string
    {
        return $this->nom_club;
    }

    public function setNomClub(string $nom_club): self
    {
        $this->nom_club = $nom_club;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->date_creation;
    }

    public function setDateCreation(\DateTimeInterface $date_creation): self
    {
        $this->date_creation = $date_creation;

        return $this;
    }

    public function getclub_owner(): ?string
    {
        return $this->club_owner;
    }

    public function setClubOwner(string $club_owner): self
    {
        $this->club_owner = $club_owner;

        return $this;
    }

    public function getnbr_members(): ?int
    {
        return $this->nbr_members;
    }

    public function setNbrMembers(int $nbr_members): self
    {
        $this->nbr_members = $nbr_members;

        return $this;
    }


    public function getImageclb()
    {
        return $this->imageclb;
    }


    public function setImageclb($imageclb)
    {
        $this->imageclb = $imageclb;
        return $this;
    }



}

src/Controller/AdminCLbController.php
<?php

namespace App\Controller;
use App\Entity\Club;
use App\Form\ClubType;
use App\Repository\ClubRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


/**
 * @Route("/clbadmin")
 */
class AdminCLbController extends AbstractController
{
    /**
     * @Route("/adminclb", name="app_adminclb_index")
     */
    public function index(ClubRepository $clubRepository): Response
    {
        return $this->render('admin_c_lb/index.html.twig', [
            'clubs' => $clubRepository->findAll(),
        ]);
    }

    /**
     * @Route("/{id}", name="app_adminclb_show", methods={"GET"})
     */
    public function show(Club $club): Response
    {
        return $this->render('admin_c_lb/adminclbshow.html.twig', [
            'club' => $club,
        ]);
    }

}

templates/admin_c_lb/adminclbshow.html.twig
{% extends 'admin.html.twig' %}

{% block title %}Club{% endblock %}

{% block body %}
    <h1>Club</h1>

    <table class="table">
        <tbody>
        <tr>
        <th>Club Image</th>
        <td><img src="{{ asset('UserPart/imgs/' ~ club.imageclb) }}"
                 alt="" style="width:200px; height: 200px "></td>
        </tr>
        <tr>
            <th>Id</th>
            <td>{{ club.id }}</td>
        </tr>
        <tr>
            <th>Nom_club</th>
            <td>{{ club.nom_club }}</td>
        </tr>
        <tr>
            <th>Date_creation</th>
            <td>{{ club.dateCreation ? club.dateCreation|date('Y-m-d') : '' }}</td>
        </tr>
        <tr>
            <th>Club_owner</th>
            <td>{{ club.club_owner }}</td>
        </tr>
        <tr>
            <th>Nbr_members</th>
            <td>{{ club.nbr_members }}</td>
        </tr>
        </tbody>
    </table>


    <B><a style="color:#642517" href="{{ path('app_adminclb_index') }}">Retour au liste des clubs</a></B>



{% endblock %}

templates/admin_c_lb/index.html.twig
{% extends 'admin.html.twig' %}

{% block title %}Club Liste{% endblock %}


{% block body %}
    <h1>Liste des clubs</h1>
    <table class="table">
        <thead>
        <tr>
            <th bgcolor="#a0bbe6" >Id Club</th>
            <th bgcolor="#a0bbe6">Nom club</th>
            <th bgcolor="#a0bbe6">Date creation</th>
            <th bgcolor="#a0bbe6">Club Owner</th>
            <th bgcolor="#a0bbe6">Nombre des membres</th>
            <th bgcolor="#a0bbe6">Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for clb in clubs %}
            <tr>
                <td>{{ clb.id }}</td>
                <td>{{ clb.nom_club }}</td>
                <td>{{ clb.dateCreation  ? clb.dateCreation |date('Y-m-d') : '' }}</td>
                <td>{{ clb.club_owner}}</td>
                <td>{{ clb.nbr_members}}</td>
                <td><img src="{{ asset('UserPart/imgs/' ~ clb.imageclb) }}"
                         alt="" style="width:40px; height: 40px "></td>

                <td>
                    <a href="{{ path('app_adminclb_show', {'id': clb.id}) }}">Détails</a>  &nbsp;
                   &nbsp;




                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">Aucun club existant</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>


{% endblock %}